PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mo: <http://www.movieontology.org/ontology/>
PREFIX imdb: <http://imdb.com/data/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

#-----------------------------------------------------------
# All the movies with title and production year
# about James Bond.
#-----------------------------------------------------------
SELECT ?movie ?title ?year
WHERE {
   ?movie a mo:Movie;
          mo:title ?title;
          mo:productionYear ?year;
          mo:hasCharacter [ mo:name "James Bond"^^xsd:string ].
}
