PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX mo: <http://www.movieontology.org/ontology/>
PREFIX imdb: <http://imdb.com/data/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

#-----------------------------------------------------------
# The production year, rating and imdbid of the movie
# named "The Matrix".
#-----------------------------------------------------------
SELECT ?movie ?production_year ?imdbid
WHERE {
  ?movie a mo:Movie;
         mo:title "The Matrix"^^xsd:string;
         mo:productionYear ?production_year;
         mo:rating ?title_rating;
         mo:imdbid ?imdbid.
}
